### ISSUE TITLE
Assignment of a special var in formula

### ISSUE THREAD

**Issue by mm95** [qsphan/boolector#1]
Hello, 
I know that this repository is not responsibility to answer the questions about boolector,
but I have a problem in using boolector python API and saw that you use this module too.
So, I determined to post my question here too.
First I parsed a smt2 file and check the satisfiability of formula with Sat() function. 
Now I want to extract the assignment to a special variable but there isn't any function to get the variables in parsed formula.
How can I do it?
For clarity, I write the below piece of code that maybe it is not correct syntactically:

//formula.smt2
(declare-fun x (_BitVector 32) () )
(assert (= x (_ bv0 32)))
....

my code :
btor = Boolector()
btor.Parse ("formula.smt2")

result = btor.Sat()
if result == btor.SAT:
   //get model and extract the assignment for var "x" , I don't know how????

Thanks so much.

**Comment by qsphan** [comment]
Hi, 

You can get the assignment string using `boolector_bv_assignment`. More details can be found here:
http://fmv.jku.at/boolector/doc/cboolector_index.html#c.boolector_bv_assignment

I hope this helps.
Sang
